
meps_list:
  output_dir: 'meps-text-mining/data/country_meps'

meps_speeches:
  europal_website: 'https://www.europarl.europa.eu'
  href_root: 'https://www.europarl.europa.eu/meps/en/'
  output_dir: 'meps-text-mining/data/meps_plenary_speeches'

  # Configure logging 
  logs_dir: 'meps-text-mining/logs'
  logs_filename: 'scraping_speeches.txt'


meps_speeches_dataframe:
  output_dir: 'meps-text-mining/data/meps_speeches_dataframe'
  filename: 'meps_speeches.csv'


meps_speeches_en_translation:
  output_dir: 'meps-text-mining/data/meps_speeches_en_translations'
  filename: 'speeches_translations.txt'
  logs_filename: 'translating_speeches.txt'
